apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "myjenkins.fullname" . }}-admin
  labels:
  {{- include "myjenkins.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'