apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myjenkins.fullname" . }}-jenkins
  labels:
  {{- include "myjenkins.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.jenkins.replicas }}
  selector:
    matchLabels:
      app: jenkins-server
    {{- include "myjenkins.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: jenkins-server
      {{- include "myjenkins.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.jenkins.jenkins.image.repository }}:{{ .Values.jenkins.jenkins.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
        name: jenkins
        ports:
        - containerPort: 8080
          name: httpport
        - containerPort: 50000
          name: jnlpport
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        resources: {{- toYaml .Values.jenkins.jenkins.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-data
      securityContext: {{- toYaml .Values.jenkins.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "myjenkins.fullname" . }}-admin
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-pv-claim