apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jenkins.fullname" . }}-jenkins-admin
  labels:
  {{- include "jenkins.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jenkins.fullname" . }}-jenkins-admin
  labels:
  {{- include "jenkins.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "jenkins.fullname" . }}-jenkins-admin'
subjects:
- kind: ServiceAccount
  name: '{{ include "jenkins.fullname" . }}-jenkins-admin'
  namespace: '{{ .Release.Namespace }}'